log:
  level: ERROR

entryPoints:
  web:
    address: :80
  app:
    address: :8081
  grpc:
    address: :9000

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

api:
  dashboard: true
