version: '3.8'

services:
  traefik:
    image: traefik:v2.7
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./conf/traefik/traefik.yaml:/etc/traefik/traefik.yaml"
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.localtest.me`)
      - traefik.http.routers.api.service=api@internal

  backend:
    build: .
    container_name: "learningsbackend"
    restart: always
    depends_on:
      - traefik
      - postgres
    env_file:
      - ./local.env
    volumes:
      - "./storage/postgres/migrations:/storage/postgres/migrations:ro"
    labels:
      - traefik.enable=true
      - traefik.http.routers.learningsbackend.rule=Host(`lea.localtest.me`)
      - traefik.http.routers.learningsbackend.service=learningsbackend
      - traefik.http.routers.learningsbackend.entrypoints=grpc
      - traefik.http.services.learningsbackend.loadbalancer.server.port=9090
      - traefik.http.services.learningsbackend.loadbalancer.server.scheme=h2c

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=example"
      - "POSTGRES_DB=postgres"
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  sqlpad:
    container_name: sqlpad
    image: sqlpad/sqlpad:latest
    hostname: sqlpad
    ports:
      - 3000:3000
    environment:
      SQLPAD_ADMIN: admin@sqlpad.com
      SQLPAD_ADMIN_PASSWORD: admin
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_CONNECTIONS__learnings__name: Learnings DB
      SQLPAD_CONNECTIONS__learnings__driver: postgres
      SQLPAD_CONNECTIONS__learnings__host: postgres
      SQLPAD_CONNECTIONS__learnings__database: postgres
      SQLPAD_CONNECTIONS__learnings__username: postgres
      SQLPAD_CONNECTIONS__learnings__password: example
      SQLPAD_CONNECTIONS__learnings__multiStatementTransactionEnabled: 'true'
      SQLPAD_CONNECTIONS__learnings__idleTimeoutSeconds: 86400

volumes:
  pgdata:
    driver: local
