// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package learnings

import (
	"database/sql"

	"github.com/google/uuid"
)

type Course struct {
	ID         uuid.UUID
	IsActive   bool
	CourseName string
}

type Material struct {
	ID          uuid.UUID
	ModuleID    uuid.UUID
	Description string
	Explanation sql.NullString
	ObjectUrl   sql.NullString
}

type Module struct {
	ID       uuid.UUID
	CourseID uuid.UUID
	NumLevel int16
}
