// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: courses.sql

package learnings

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCourse = `-- name: AddCourse :one
INSERT INTO
    courses (id, is_active, course_name, created_at, updated_at)
VALUES
    ($1, $2, $3, $4, $5) RETURNING id, category_id, is_active, course_name, created_at, updated_at
`

type AddCourseParams struct {
	ID         uuid.UUID
	IsActive   bool
	CourseName string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) AddCourse(ctx context.Context, arg AddCourseParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, addCourse,
		arg.ID,
		arg.IsActive,
		arg.CourseName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.IsActive,
		&i.CourseName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT
    id, category_id, is_active, course_name, created_at, updated_at
FROM
    courses
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.IsActive,
			&i.CourseName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
