// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package learnings

import (
	"github.com/google/uuid"
)

type Category struct {
	ID    uuid.UUID
	Label string
}

type Course struct {
	ID         uuid.UUID
	CategoryID uuid.UUID
	IsActive   bool
	CourseName string
}

type Material struct {
	ID          uuid.UUID
	ModuleID    uuid.UUID
	Description string
	Explanation string
	ObjectUrl   string
}

type Module struct {
	ID              uuid.UUID
	CourseID        uuid.UUID
	ExperienceLevel int16
}
